apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: openwms-services
  namespace: default
spec:
  runLatest:
    configuration:
      revisionTemplate:
        metadata:
          annotations:
            autoscaling.knative.dev/minScale: "1"
            autoscaling.knative.dev/maxScale: "5"
        spec:
          container:
            image: docker.io/interface21/openwms-services:latest
            ports:
              - containerPort: 8080
